NOJIRA-46: move heredoc to another executable

diff --git a/git_delete_stale_branches/usr/local/bin/git_delete_stale_branches b/git_delete_stale_branches/usr/local/bin/git_delete_stale_branches
--- a/git_delete_stale_branches/usr/local/bin/git_delete_stale_branches
+++ b/git_delete_stale_branches/usr/local/bin/git_delete_stale_branches
@@ -4,7 +4,7 @@
 set -euo pipefail
 
 REFERENCE_DIR="${REFERENCE_DIR:-}"
-source "${REFERENCE_DIR}"/usr/local/lib/git_delete_stale_branches/git_delete_stale_branches
+source "${REFERENCE_DIR}/usr/local/lib/git_delete_stale_branches/git_delete_stale_branches"
 source /usr/local/lib/shell_argument_parsing_file/shell_argument_parsing_file
 
 REC_ENTRYPOINT=${REFERENCE_DIR}/usr/local/share/git_delete_stale_branches/recfiles/git_delete_stale_branches_entrypoint.rec
@@ -29,7 +29,7 @@ fi
 # _associative_arrays_are_equal empty_array arguments
 
 # ✂ --------------------------------------------------
-validate_other_git_branches_deleted_file() {
+function validate_other_git_branches_deleted_file() {
     validated="$(grep -E '^[0-9]+,.*$' -- "${1}")"
     if diff <(printf "%s\n" "${validated}") "${1}"; then
         return 0
@@ -75,6 +75,11 @@ fi
 
 official_file="$(readlink -f "${config_directory}/official")"
 
+if [[ ! -f ${official_file} ]]; then
+    echo "Official branch file «${official_file}» not found." > /dev/stderr
+    exit 1
+fi
+
 validate_other_git_branches_deleted_file "${delete_file}"
 
 # Go to execution directory.
@@ -82,56 +87,7 @@ cd "${git_directory}"
 git rev-parse --git-dir 2> /dev/null
 
 while IFS=, read -r date_ branch_; do
-    bash -s -- "${date_}" "${branch_}" ${official_file} << 'EOF'
-#! /usr/bin/env bash
-
-# Halt on error.
-set -euxo pipefail
-
-official_file="${3}"
-delete_file="$(basename "${official_file}")/deleted"
-
-official_branch="$(cat ${official_file})"
-[[ -n ${official_branch} ]]
-[[ $(wc -l <<< ${official_branch}) -eq 1 ]]
-
-[[ ${official_branch} != ${2} ]]
-
-# If the last commit time of this branch comes before the deletion timestamp we
-# are ok to delete it.
-set +o pipefail
-last_commit_of_branch="$(git log --format='%at' "${2}" | head -n 1)"
-set -o pipefail
-# If `last_commit_of_branch` is empty assume remote `origin`.
-#
-# ???: This is a shortcut
-#
-if [[ -z $last_commit_of_branch ]]; then
-    set +o pipefail
-    last_commit_of_branch="$(git log --format='%at' "origin/${2}" | head -n 1)"
-    set -o pipefail
-fi
-re='^[0-9]+$'
-if ! [[ $last_commit_of_branch =~ $re ]]; then
-    # ???: should we make these cases distinct? (i.e. "not being a number" and
-    # "already being deleted".
-    echo "error: '${last_commit_of_branch}' not a number or already deleted." >&2
-    exit 0
-fi
-if [[ ${last_commit_of_branch} > ${1} ]]; then
-    echo "error: '${last_commit_of_branch}' comes after the saved timestamp ('${2}')." >&2
-    exit 0
-fi
-
-git branch --all \
-    | sed -E 's/.* //g' \
-    | sed -E 's#.*/##g' \
-    | grep --fixed-strings --line-regexp --regexp "${2}" \
-    || exit 0
-
-git branch --force --delete "${2}" || true
-git push --force --delete origin "${2}" || true
-EOF
+    "${REFERENCE_DIR}/usr/local/libexec/git_delete_stale_branch" "${date_}" "${branch_}" "${official_file}"
 done < "${delete_file}"
 
 # vim: set filetype=sh fileformat=unix nowrap:
