NOJIRA-46: add new feature: 3 field CSV with delayed deletion

diff --git a/git_delete_stale_branches/usr/local/bin/git_delete_stale_branches b/git_delete_stale_branches/usr/local/bin/git_delete_stale_branches
--- a/git_delete_stale_branches/usr/local/bin/git_delete_stale_branches
+++ b/git_delete_stale_branches/usr/local/bin/git_delete_stale_branches
@@ -4,7 +4,7 @@
 set -euo pipefail
 
 REFERENCE_DIR="${REFERENCE_DIR:-}"
-source "${REFERENCE_DIR}"/usr/local/lib/git_delete_stale_branches/git_delete_stale_branches
+source "${REFERENCE_DIR}/usr/local/lib/git_delete_stale_branches/git_delete_stale_branches"
 source /usr/local/lib/shell_argument_parsing_file/shell_argument_parsing_file
 
 REC_ENTRYPOINT=${REFERENCE_DIR}/usr/local/share/git_delete_stale_branches/recfiles/git_delete_stale_branches_entrypoint.rec
@@ -29,14 +29,6 @@ fi
 # _associative_arrays_are_equal empty_array arguments
 
 # ✂ --------------------------------------------------
-validate_other_git_branches_deleted_file() {
-    validated="$(grep -E '^[0-9]+,.*$' -- "${1}")"
-    if diff <(printf "%s\n" "${validated}") "${1}"; then
-        return 0
-    else
-        return 1
-    fi
-}
 
 expected_number_of_arguments=5
 
@@ -56,7 +48,7 @@ fi
 # Unquote the argument.
 config_directory="$(echo "${arguments['config-directory']}" | xargs echo)"
 if ! [[ -d ${config_directory} ]]; then
-    echo "The second argument should be a git directory (was '${config_directory}')." > /dev/stderr
+    echo "The second argument should be a directory (was '${config_directory}')." > /dev/stderr
     exit 1
 fi
 
@@ -75,85 +67,39 @@ fi
 
 official_file="$(readlink -f "${config_directory}/official")"
 
-validate_other_git_branches_deleted_file "${delete_file}"
+if [[ ! -f ${official_file} ]]; then
+    echo "Official branch file «${official_file}» not found." > /dev/stderr
+    exit 1
+fi
 
 # Go to execution directory.
 cd "${git_directory}"
-git rev-parse --git-dir 2> /dev/null
-
-while IFS=, read -r date_ branch_; do
-    bash -s -- "${date_}" "${branch_}" ${official_file} << 'EOF'
-#! /usr/bin/env bash
-
-# Halt on error.
-set -euxo pipefail
-
-official_file="${3}"
-delete_file="$(basename "${official_file}")/deleted"
-
-official_branch="$(cat ${official_file})"
-[[ -n ${official_branch} ]]
-[[ $(wc -l <<< ${official_branch}) -eq 1 ]]
-
-[[ ${official_branch} != ${2} ]]
-
-# If the last commit time of this branch comes before the deletion timestamp we
-# are ok to delete it.
-set +o pipefail
-last_commit_of_branch="$(git log --format='%at' "${2}" | head -n 1)"
-set -o pipefail
-# If `last_commit_of_branch` is empty assume remote `origin`.
-#
-# ???: This is a shortcut
-#
-if [[ -z $last_commit_of_branch ]]; then
-    set +o pipefail
-    last_commit_of_branch="$(git log --format='%at' "origin/${2}" | head -n 1)"
-    set -o pipefail
-fi
-re='^[0-9]+$'
-if ! [[ $last_commit_of_branch =~ $re ]]; then
-    # ???: should we make these cases distinct? (i.e. "not being a number" and
-    # "already being deleted".
-    echo "error: '${last_commit_of_branch}' not a number or already deleted." >&2
-    exit 0
-fi
-if [[ ${last_commit_of_branch} > ${1} ]]; then
-    echo "error: '${last_commit_of_branch}' comes after the saved timestamp ('${2}')." >&2
-    exit 0
+if git rev-parse --git-dir 2> /dev/null; then
+    :
+else
+    echo "The «${git_directory}» is not a valid git directory." > /dev/stderr
+    exit 1
 fi
 
-git branch --all \
-    | sed -E 's/.* //g' \
-    | sed -E 's#.*/##g' \
-    | grep --fixed-strings --line-regexp --regexp "${2}" \
-    || exit 0
-
-git branch --force --delete "${2}" || true
-git push --force --delete origin "${2}" || true
-EOF
-done < "${delete_file}"
-
-# vim: set filetype=sh fileformat=unix nowrap:
-# -------------------------------------------------- ✂
-
-# if [[ ${arguments[help]:-false} == 'true' ]]; then
-#     git_delete_stale_branches_help
-#     exit 0
-# fi
+# As of `v0.1.x` we are supporting a 3 column CSV.
 #
-# if [[ ${arguments[verbose]:-false} == 'true' ]]; then
-#     bash ${REFERENCE_DIR}/usr/local/share/git_delete_stale_branches/tests/test_01.sh --test
-#     set -x
-# fi
+# * CSV "schema" for the original 2 field use case:
 #
-# if [[ ${arguments[test]:-SENTINEL} != 'SENTINEL' ]]; then
-#     bash ${REFERENCE_DIR}/usr/local/share/git_delete_stale_branches/tests/test_01.sh --test
-# else
-#     echo "Unrecognized entrypoint: \`$@\`." > /dev/stderr
-#     exit 1
-# fi
+#   ```
+#   timestamp_delete_if_commit_is_older,branch
+#   1739817094,nojira_81
+#   ```
 #
-# echo "Tests are done." > /dev/stderr
+# * CSV "schema" for the original 3 field use case:
+#
+#   ```
+#   timestamp_delete_if_commit_is_older,branch,timestamp_delete_after
+#   1739817094,nojira_81,1741366313
+#   ```
+
+print_normalized_csv "${delete_file}" \
+    | while IFS=, read -r timestamp_delete_if_commit_is_older_ branch_ timestamp_delete_after; do
+        "${REFERENCE_DIR}/usr/local/libexec/git_delete_stale_branch" "${timestamp_delete_if_commit_is_older_}" "${branch_}" "${timestamp_delete_after}" "${official_file}" "$(date '+%s')"
+    done
 
 # vim: set filetype=sh fileformat=unix nowrap:
diff --git a/other/test/docker/host_test_02 b/other/test/docker/host_test_02
--- a/other/test/docker/host_test_02
+++ b/other/test/docker/host_test_02
@@ -1,11 +1,76 @@
 #! /usr/bin/env bash
 #
-# shellcheck disable=SC2251
+# ```
+# bash -xv other/test/docker/docker_test_02
+# ```
+#
+# Test using a non conventional directory structure.
 
 # Halt on error.
 set -euo pipefail
 
-# `commb1f40e0`: see this to re enable this test.
-exit 0
+source ./other/test/docker/test_lib
+
+# Go to execution directory.
+cd "$(git rev-parse --show-toplevel)"
+curdir=$(pwd)
+
+tarball="$(readlink --canonicalize './other/test/data/fake_repos_02.tar')"
+
+tmpdir="$(mktemp_gdsb)"
+[[ -n ${tmpdir} ]]
+[[ ${tmpdir} =~ ^/tmp/ ]]
+
+cd "${tmpdir}"
+tar -xf "${tarball}"
+cd ./git_delete_stale_branches_fake_git_repos_02
+
+[[ -d .git ]]
+
+# Create a new branch.
+git checkout main
+git checkout -b branch03
+echo 'busy work branch03' > busy_$(uuidgen | sed -E 's/-//g').txt
+git add --force -- .
+git commit -m "added busy work branch03"
+git checkout main
+
+mkdir another/
+mv other/git/branches/ another/branches
+pwd | xclip
+"${REFERENCE_DIR}/usr/local/bin/git_delete_stale_branches" --delete --git-directory "$(pwd)" --config-directory "./another/branches"
+
+set -x
+[[ "$(git branch -a | sort -u)" == "$(echo '
+  branch01
+  branch03
+* main
+' | sed --regexp-extended '/^$/d')" ]]
+
+# Ensure `timestamp_delete_after` is working.
+git checkout -b branch04
+git commit --allow-empty -m "added branch04"
+git checkout main
+delay=3
+now_="$(date '+%s')"
+now_little_ahead_in_the_future="$((now_ + 2))"
+now_more_ahead_in_the_future="$((now_ + delay))"
+echo "${now_little_ahead_in_the_future},branch04,${now_more_ahead_in_the_future}" >> ./another/branches/deleted
+"${REFERENCE_DIR}/usr/local/bin/git_delete_stale_branches" --delete --git-directory "$(pwd)" --config-directory "./another/branches"
+if git branch -a | grep --extended-regexp 'branch04'; then
+    :
+else
+    echo "Branch «branch04» not found." > /dev/stderr
+    exit 1
+fi
+
+sleep $((delay + 1))
+"${REFERENCE_DIR}/usr/local/bin/git_delete_stale_branches" --delete --git-directory "$(pwd)" --config-directory "./another/branches"
+if git branch -a | grep --extended-regexp 'branch04'; then
+    echo "Branch «branch04» found (and it should be deleted)." > /dev/stderr
+    exit 1
+else
+    :
+fi
 
 # vim: set filetype=sh fileformat=unix nowrap:
